#!/bin/sh

pgrep -x sxhkd > /dev/null && pkill -USR1 -x sxhkd || sxhkd &
xrdb ~/.Xresources

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width $(xrdbget wm.borderWidth)
bspc config window_gap $(xrdbget wm.windowGap)

bspc config active_border_color "$(xrdbget wm.borderColorActive)"
bspc config normal_border_color "$(xrdbget wm.borderColorNormal)"
bspc config focused_border_color "$(xrdbget wm.borderColorFocused)"

bspc config split_ratio $(xrdbget wm.splitRatio)

scr_random_wallpaper
